# Generated by Django 3.2.9 on 2021-11-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0003_auto_20211105_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
