# Generated by Django 3.2.9 on 2021-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0006_alter_statistic_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
