# Generated by Django 3.2.9 on 2021-11-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sport', '0009_auto_20211108_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Sport.statistic'),
        ),
    ]
